services:
  - type: web
    name: lunar-event-management
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar --spring.profiles.active=prod
    healthCheckPath: /api/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: lunar-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: RAZORPAY_WEBHOOK_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

databases:
  - name: lunar-postgres
    databaseName: lunar_events
    user: lunar_user
